---
# tasks file for mysql-import

- name: Dump MySQL username variable
  debug: msg="MySQL Username is {{ mysql_users.name | mandatory }}"

- name: Dump MySQL password variable
  debug: msg="MySQL Password is {{ mysql_users.password | mandatory }}"

- name: Dump MySQL root password variable
  debug: msg="MySQL Root Password is {{ db_root_password | mandatory }}"

- name: Dump Bitbucket username variable
  debug: msg="Bitbucket Username is {{ bitbucket_user | mandatory }}"

- name: Dump Bitbucket username variable
  debug: msg="Bitbucket Password is {{ bitbucket_password | mandatory }}"

- name: Dump variables of database names
  debug: msg=Database name is "{{ item.name }}" and SQL file is "{{ item.sqlfile }}"
  with_items: "{{ mysql_databases }}"

- name: Pause to examine variables
  pause: seconds=5 prompt="Examine the above variables"

#- name: Import MySQL databases from SQL.
#  mysql_db:
#    name: "{{ item.name }}"
#    target: "{{ item.sqlfile }}"
#    state: import
#    login_user: "{{ mysql_users.name }}"
#    login_password: "{{ mysql_users.password }}"
#  with_items: "{{ mysql_databases }}"

